#!/bin/sh
set -eu

fail() {
    printf '%s\n' "$*" >&2
    exit 1
}

case $# in
    4)
        source_owner=$1
        repository=$2
        destination_owner=$3
        expected_login=$4
        output=transfer-${repository}-from-${source_owner}-to-${destination_owner}.sh
        ;;
    5)
        source_owner=$1
        repository=$2
        destination_owner=$3
        expected_login=$4
        output=$5
        ;;
    *)
        fail 'usage: generate-transfer-github-repository-script.sh SOURCE_OWNER REPOSITORY DESTINATION_OWNER EXPECTED_LOGIN [OUTPUT]'
        ;;
esac

for value in "$source_owner" "$repository" "$destination_owner" "$expected_login"; do
    case $value in
        ''|*[!A-Za-z0-9_.-]*)
            fail "unsafe GitHub name component: $value"
            ;;
    esac
done

case $output in
    ''|*/)
        fail 'output must name a file'
        ;;
esac

here=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
candidate=$here/1.sh

[ -r "$candidate" ] || fail "cannot read versioned candidate: $candidate"
[ ! -e "$output" ] || fail "refusing to overwrite existing output: $output"

umask 077
tmp=$output.tmp.$$
trap 'rm -f "$tmp"' EXIT HUP INT TERM

awk \
    -v source_owner="$source_owner" \
    -v repository="$repository" \
    -v destination_owner="$destination_owner" \
    -v expected_login="$expected_login" '
NR == 1 {
    print
    print "# Generated by generate-transfer-github-repository-script.sh."
    print "# This file is standalone; the numbered Kitchen candidate is not needed at runtime."
    next
}

$0 == "[ \"$#\" -eq 4 ] ||" {
    replacing = 1
    print ""
    print "source_owner=" source_owner
    print "repository=" repository
    print "destination_owner=" destination_owner
    print "expected_login=" expected_login
    next
}

replacing {
    if ($0 == "expected_login=$4") {
        replacing = 0
    }
    next
}

{
    print
}
' "$candidate" >"$tmp"

grep -F "source_owner=$source_owner" "$tmp" >/dev/null ||
    fail 'generated script is missing the bound source owner'
grep -F "repository=$repository" "$tmp" >/dev/null ||
    fail 'generated script is missing the bound repository'
grep -F "destination_owner=$destination_owner" "$tmp" >/dev/null ||
    fail 'generated script is missing the bound destination owner'
grep -F "expected_login=$expected_login" "$tmp" >/dev/null ||
    fail 'generated script is missing the bound expected login'

if grep -F 'usage: 1.sh' "$tmp" >/dev/null; then
    fail 'generated script still exposes the numbered candidate interface'
fi

chmod 700 "$tmp"
mv "$tmp" "$output"
trap - EXIT HUP INT TERM

printf '%s\n' "$output"
