#!/opt/catfood/bin/grease
# Grease; candidate 1 and its historical evidence remain unchanged.
proc fail (...messages) { echo @messages >&2; exit 2 }
if (len(ARGV) !== 6) { fail 'usage: generator SOURCE REPOSITORY DESTINATION LOGIN NUMERIC_ID CONTEXT' }
var source_owner = ARGV[0]
var repository = ARGV[1]
var destination_owner = ARGV[2]
var expected_login = ARGV[3]
var expected_repository_id = ARGV[4]
var target_context = ARGV[5]
for value in @ARGV {
  if ! /usr/bin/grep -Eq '^[A-Za-z0-9][A-Za-z0-9_.-]*$' <<< "$value" { fail 'invalid input component' }
}
if ! /usr/bin/grep -Eq '^[1-9][0-9]*$' <<< "$expected_repository_id" { fail 'repository ID must be positive' }
if (target_context !== 'linux-x86_64-grease-v1') { fail 'unqualified execution context' }
var output = "transfer-${repository}-from-${source_owner}-to-${destination_owner}.sh"
if test -e "$output" { fail 'output already exists' }
var here = $(dirname -- "$0")
umask 077
set -o noclobber
{
  echo '#!/opt/catfood/bin/grease'
  echo '# Standalone Grease artifact. Generated by the maintained Kitchen recipe.'
  printf 'var source_owner = "%s"\nvar repository = "%s"\nvar destination_owner = "%s"\nvar expected_login = "%s"\nvar expected_repository_id = %s\nvar target_context = "%s"\n' "$source_owner" "$repository" "$destination_owner" "$expected_login" "$expected_repository_id" "$target_context"
  cat -- "$here/5.sh"
} > "$output"
chmod 700 -- "$output"
echo "$output"
