import importlib.util
import os
from pathlib import Path
import shutil
import subprocess
import sys
import tempfile
import unittest

HERE = Path(__file__).resolve().parent
WRAPPER = Path(os.environ.get("KITCHEN_WRAPPER", HERE / "1.py"))
ENGINE = Path(os.environ["MBOX_ENGINE"])
spec = importlib.util.spec_from_file_location("gate", HERE / "gate.py")
gate = importlib.util.module_from_spec(spec)
spec.loader.exec_module(gate)


class HandoffTests(unittest.TestCase):
    def test_exact_wrapper_from_unrelated_directories(self):
        selected = b"From x\nSubject: SPEC-LIST\nMessage-ID: <same>\n\nselected\xff\n"
        kept = b"From x\nSubject: keep\n\nSPEC-LIST in body\n"
        for location in ("outside-one", "outside two spaces"):
            with self.subTest(location=location), tempfile.TemporaryDirectory() as temporary:
                root = Path(temporary)
                (root / "DISPOSABLE-MAILBOX-TEST-ONLY").touch()
                source = root / "incoming"
                archive = root / "archive"
                source.write_bytes(selected + kept + selected)
                elsewhere = root / location
                elsewhere.mkdir()
                for mode in ("inspect", "copy", "move"):
                    command = [sys.executable, str(WRAPPER), "--engine", str(ENGINE), "plan", "--source", str(source),
                               "--destination", str(archive), "--mode", mode]
                    result = subprocess.run(command, cwd=elsewhere, capture_output=True)
                    self.assertEqual(result.returncode, 0, result.stderr)
                    self.assertEqual(source.read_bytes(), selected + kept + selected)
                    self.assertFalse(archive.exists())
                    self.assertIn(b"mode\t" + mode.encode(), result.stdout)
                    self.assertIn(b"summary\t3\t2\t", result.stdout)
                    if mode == "move":
                        plan = root / "plan.tsv"
                        plan.write_bytes(result.stdout)
                live = subprocess.run(command + ["--live-spool"], cwd=elsewhere, capture_output=True)
                self.assertNotEqual(live.returncode, 0)
                mutation = [sys.executable, str(WRAPPER), "--engine", str(ENGINE), "execute-disposable",
                            "--plan", str(plan), "--disposable-root", str(root)]
                result = subprocess.run(mutation, cwd=elsewhere, capture_output=True)
                self.assertEqual(result.returncode, 0, result.stderr)
                self.assertEqual(source.read_bytes(), kept)
                self.assertEqual(archive.read_bytes(), selected + selected)
                self.assertEqual(subprocess.run(mutation, cwd=elsewhere).returncode, 0)

    def test_gate_rejects_post_test_drift_and_accepts_control(self):
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            # Preserve the normal bundle topology so it includes test/fixture bytes.
            engine = root / "mbox/examples/autogenerated/safe-filing"
            engine.parent.mkdir(parents=True)
            shutil.copytree(ENGINE, engine)
            mbox = ENGINE.parents[2]
            for name in ("tests/hardening", "fixtures"):
                shutil.copytree(mbox / name, root / "mbox" / name)
            shutil.copyfile(mbox / "CONTRACT.md", root / "mbox/CONTRACT.md")
            wrapper = root / "displayed.py"
            shutil.copyfile(WRAPPER, wrapper)
            argv = [sys.executable, str(wrapper), "--engine", str(engine), "plan", "--source", "/var/mail/isomorphisms",
                    "--destination", "/sdf/arpa/gm/i/isomorphisms/Mail/spec-list", "--mode", "copy", "--live-spool"]
            receipt = root / "tested.tsv"
            # Lower-level verification unit fixture; qualify() is the only CLI
            # producer and runs all actual suites before issuing this structure.
            receipt.write_text("tests\tPASS\n" + gate.content(wrapper, engine, argv))
            gate.verify(receipt, wrapper, engine, argv)
            for name, change in (
                ("version-B", lambda: wrapper.write_text(wrapper.read_text() + "\n# B\n")),
                ("selector", lambda: (engine / "spec_list.py").write_text("SEARCH_HEADERS=()\n")),
                ("library", lambda: (engine / "filing.py").write_text("pass\n")),
                ("fixture", lambda: (root / "mbox/tests/hardening/corpus.py").write_text("pass\n"))):
                with self.subTest(mutant=name):
                    snapshots = {path: path.read_bytes() for path in (wrapper, engine / "spec_list.py", engine / "filing.py",
                                 root / "mbox/tests/hardening/corpus.py")}
                    change()
                    with self.assertRaises(RuntimeError):
                        gate.verify(receipt, wrapper, engine, argv)
                    for path, data in snapshots.items():
                        path.write_bytes(data)
                    gate.verify(receipt, wrapper, engine, argv)
            for name, changed in (
                ("copy-to-move", ["move" if x == "copy" else x for x in argv]),
                ("home-mailbox", ["/sdf/arpa/gm/i/isomorphisms/mbox" if x == "/var/mail/isomorphisms" else x for x in argv]),
                ("swapped-roles", [argv[8] if i == 6 else argv[6] if i == 8 else x for i, x in enumerate(argv)]),
                ("untested-wrapper", [sys.executable, str(wrapper) + ".new"] + argv[2:]),
                ("different-output", ["/tmp/other" if x.endswith("/Mail/spec-list") else x for x in argv])):
                with self.subTest(mutant=name), self.assertRaises(RuntimeError):
                    gate.verify(receipt, wrapper, engine, changed)
            receipt.write_text(receipt.read_text().replace("tests\tPASS", "tests\tNOT_RUN"))
            with self.assertRaises(RuntimeError):
                gate.verify(receipt, wrapper, engine, argv)


if __name__ == "__main__":
    unittest.main(verbosity=2)
